import { Writable } from '@ctx-core/store';
import type { maybe_null } from '@ctx-core/function';
export declare const b__auth0Lock: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => Writable<null>;
export declare const __auth0Lock: Writable<null>;
export declare type $type__logout_Auth0Lock = () => Promise<void>;
export declare type $maybe_type__logout_Auth0Lock = maybe_null<$type__logout_Auth0Lock>;
export declare type type__logout_Auth0Lock = Writable<$maybe_type__logout_Auth0Lock>;
export declare const b__logout_Auth0Lock: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => type__logout_Auth0Lock;
export declare const __logout_Auth0Lock: type__logout_Auth0Lock;
export declare const b__AUTH0_CLIENT_ID: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => Writable<null>;
export declare const __AUTH0_CLIENT_ID: Writable<null>;
export declare const b__AUTH0_DOMAIN: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => Writable<null>;
export declare const __AUTH0_DOMAIN: Writable<null>;
