import { Writable } from '@ctx-core/store';
import type Auth0Lock from 'auth0-lock';
export declare const b__auth0Lock: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => Writable<Auth0LockStatic | null>;
export declare type $auth0Lock_type = typeof Auth0Lock;
export declare const b__logout_Auth0Lock: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => type__logout_Auth0Lock;
export declare const __auth0Lock: Writable<Auth0LockStatic | null>;
export declare type $type__logout_Auth0Lock = () => Promise<void>;
export declare type $maybe_type__logout_Auth0Lock = $type__logout_Auth0Lock | null;
export declare type type__logout_Auth0Lock = Writable<$maybe_type__logout_Auth0Lock>;
export declare const __logout_Auth0Lock: type__logout_Auth0Lock;
export declare const b__AUTH0_CLIENT_ID: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => AUTH0_CLIENT_ID_type;
export declare const __AUTH0_CLIENT_ID: AUTH0_CLIENT_ID_type;
export declare type $AUTH0_CLIENT_ID_type = string;
export declare type AUTH0_CLIENT_ID_type = Writable<$AUTH0_CLIENT_ID_type>;
export declare const b__AUTH0_DOMAIN: (ctx?: object | undefined, opts?: import("@ctx-core/object")._be_opts_type | undefined) => AUTH0_DOMAIN_type;
export declare const __AUTH0_DOMAIN: AUTH0_DOMAIN_type;
export declare type $AUTH0_DOMAIN_type = string;
export declare type AUTH0_DOMAIN_type = Writable<$AUTH0_DOMAIN_type>;
