/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { auth0_lock$_T } from './auth0_lock$_b.js'
import type { auth0_lock_client__T } from './auth0_lock_client__b.js'
import type { logout_auth0_lock_T } from './logout_auth0_lock_b.js'
export interface auth0_lock_ctx_I {
	auth0_lock$?:auth0_lock$_T
	auth0_lock_client_?:auth0_lock_client__T
	logout_auth0_lock?:logout_auth0_lock_T
}
