/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { _b } from '@ctx-core/object'
import type { auth0_lock$_T } from './auth0_lock$_b'
import { auth0_lock$_b } from './auth0_lock$_b'
import type { auth0_lock_client__T } from './auth0_lock_client__b'
import { auth0_lock_client__b } from './auth0_lock_client__b'
import type { logout_auth0_lock_T } from './logout_auth0_lock_b'
import { logout_auth0_lock_b } from './logout_auth0_lock_b'
export interface auth0_lock_ctx_I {
	auth0_lock$?:auth0_lock$_T
	auth0_lock_client_?:auth0_lock_client__T
	logout_auth0_lock?:logout_auth0_lock_T
	auth0_lock_b_h?:auth0_lock_b_h_T
}
export interface auth0_lock_b_h_T {
	get auth0_lock$():auth0_lock$_T
	get auth0_lock_client_():auth0_lock_client__T
	get logout_auth0_lock():logout_auth0_lock_T
}
export function auth0_lock_b_h_b(ctx:auth0_lock_ctx_I):auth0_lock_b_h_T {
	return _b<auth0_lock_ctx_I, 'auth0_lock_b_h'>('auth0_lock_b_h', ()=>{
		return {
			get auth0_lock$() { return auth0_lock$_b(ctx) },
			get auth0_lock_client_() { return auth0_lock_client__b(ctx) },
			get logout_auth0_lock() { return logout_auth0_lock_b(ctx) }
		}
	})(ctx)
}